# Install dependencies only when needed
FROM node:16-alpine 

ENV WORKDIR=/usr/local/build
RUN apk add --no-cache libc6-compat
WORKDIR $WORKDIR
COPY package.json package-lock.json ./
RUN npm install 

COPY . .



EXPOSE 3000/tcp

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]

CMD ["npm", "run", "webserver"]
